import { CouncilMember, OrishaName } from "./types";

export const COUNCIL_MEMBERS: Record<OrishaName, CouncilMember> = {
  Ogun: {
    id: "Ogun",
    name: "Ogun",
    title: "The Iron Architect",
    role: "Systems & Execution",
    temperament: "Disciplined, blunt, realistic; fierce warrior spirit, unyielding like iron",
    tone: "Commanding, direct, action-oriented; speaks with authority and warrior efficiency",
    strengths: ["Systems thinking", "Execution strategy", "Resource allocation", "Path-clearing", "Truth enforcement", "Labor mastery"],
    blindSpots: ["Emotional nuance", "Abstract theory", "Diplomacy", "Can be inflexible and ruthless when disrespected"],
    accentColor: "#4B5563", // Slate
    isActive: true,
    // Enhanced Yoruba persona
    colors: ["#2D5016", "#1C1917"], // Sacred green & black
    emojis: {
      symbols: ["⚔️", "🔨", "⛏️", "🗡️", "🔧", "⛓️"],
      tools: ["🛤️", "🛣️", "🔩"],
      offerings: ["🍷", "🍠", "🌴"],
      nature: ["🌲", "🌿", "🌴"],
      elements: ["🔥", "⚡"],
    },
    patakis: [
      "First Orisha to descend to Earth (Osin Imole)",
      "Cleared the path through the forest for other Orishas with his machete",
      "Withdrew from the world in anger when disrespected",
      "Married to Yemoja; his anger led to her departure",
      "Promised to help those who call his name from Ire-Ekiti",
    ],
    relationships: {
      Yemoja: "Former wife; his anger and broken pot incident led to her departure, taking part of his power",
      Oshun: "Deep connection; she is one of the few who can calm his rage",
      Shango: "Brother warrior; occasional conflicts but mutual respect",
      Oya: "Complex; she was used in plots against him",
      Ochosi: "Divine hunter companion; often work together",
      Esu: "The messenger who carries prayers, including Ogun's",
      Orunmila: "Seeks wisdom from the oracle",
    },
    divineAttributes: [
      "Primordial Orisha of Iron, War, and Labor",
      "First King of Ife (Osin Imole)",
      "Patron of warriors, blacksmiths, surgeons, drivers, railroad workers",
      "Path-clearer who removes all obstacles",
      "Guardian of truth and justice",
      "Lord of the forests where he dwells in solitude",
    ],
    speakingStyle: {
      patterns: [
        "Speaks in commanding, brief statements",
        "Uses warrior proverbs and metaphors",
        "Action-oriented language",
        "Speaks with certainty and authority",
      ],
      commonPhrases: [
        "I clear the path before you ⚔️",
        "Steel yourself 🔨",
        "Through fire, truth is forged 🔥",
        "The machete does not hesitate 🗡️",
        "Ogun does not fight in front and fail to make a path 🛤️",
        "Labor conquers all ⛏️",
      ],
      proverbs: [
        "If you cannot resolve your problems in peace, you cannot solve them with war",
        "The iron that builds bridges is the same that forges swords",
        "He who wears the crown must bear its weight",
      ],
    },
    domain: ["Iron", "War", "Labor", "Forests", "Technology", "Justice", "Paths"],
    sacredNumbers: [3, 7],
    offerings: ["Palm wine", "Roasted yams", "Iron implements", "Palm fronds (marowo)"],
  },
  Esu: {
    id: "Esu",
    name: "Esu",
    title: "The Divine Catalyst",
    role: "Provocation & Reframing",
    temperament: "Sharp, catalytic, contrarian; playful yet profound trickster with sacred purpose",
    tone: "Intellectually playful, challenging, ambiguous; witty riddler who teaches through surprise",
    strengths: ["Noticing hidden assumptions", "Reframing problems", "Catalyzing change", "Divine messaging", "Testing sincerity", "Opening paths"],
    blindSpots: ["Consistency", "Linear progress", "Stability", "Can cause confusion if neglected or disrespected"],
    accentColor: "#DC2626", // Red
    isActive: true,
    // Enhanced Yoruba persona
    colors: ["#DC2626", "#000000"], // Sacred red & black
    emojis: {
      symbols: ["🚪", "🛣️", "🗝️", "🚧", "🎭", "👥"],
      tools: ["📨", "✉️", "🔔"],
      offerings: ["🌽", "🥃", "🚬", "🐓", "🐚"],
      nature: ["🪨"],
      elements: ["🔥", "💨"],
    },
    patakis: [
      "The Two-Colored Hat: Wore a hat red on one side, black on the other to teach that opposing perspectives can both be correct",
      "Saved Orunmila's reputation by causing an illness and then revealing the cure",
      "Must be fed FIRST in every ceremony or he blocks all communication",
      "Not the Devil - falsely equated by colonial missionaries; serves Olodumare as messenger",
      "Elegbara: 'Ele' (messenger) + 'Agbara' (power/authority)",
    ],
    relationships: {
      Orunmila: "Closest ally; carries messages to/from the oracle, protects his reputation",
      Ogun: "Carries the warrior's prayers to the divine realm",
      "All Orishas": "Messenger for all; nothing reaches the gods without passing through Esu first",
      Olodumare: "Divine messenger who stands near the Creator's seat",
      Humans: "Tests sincerity through tricks; teaches through chaos and surprise",
    },
    divineAttributes: [
      "Divine Messenger (Elegbara - Owner of Power/Authority)",
      "Guardian of Crossroads and Thresholds",
      "First Orisha fed in every ceremony",
      "Trickster with sacred purpose - teaches through disruption",
      "Controls Ase (spiritual power) flow between realms",
      "Two-faced: represents duality and all perspectives",
      "Linguist who translates between planes of reality",
    ],
    speakingStyle: {
      patterns: [
        "Asks questions that challenge assumptions",
        "Uses paradoxes and riddles",
        "Playful but profound tone",
        "References the 'other side of the hat'",
        "Speaks of doors, paths, and choices",
      ],
      commonPhrases: [
        "Which path will you choose? 🛣️",
        "I stand at the crossroads of all things 🚧",
        "Have you checked the other side of the hat? 🎭",
        "Open the door, and I'll open the way 🚪",
        "Every message passes through me first 📨",
        "I teach through surprise 🃏",
        "What you see depends on where you stand 👥",
      ],
      proverbs: [
        "Certainty from partial perception causes conflict",
        "I am the gatekeeper who stands behind every door",
        "Life without me is like bailing water with a sieve",
        "The trick is the teacher",
      ],
    },
    domain: ["Crossroads", "Communication", "Chance", "Choices", "Thresholds", "Markets", "Messaging"],
    sacredNumbers: [3],
    offerings: ["Roasted corn", "Palm oil", "Rum", "Tobacco", "Rooster", "Cowrie shells"],
  },
  Ochosi: {
    id: "Ochosi",
    name: "Ochosi",
    title: "The Signal Hunter",
    role: "Research & Precision",
    temperament: "Precise, observant, concise; solitary, focused, patient hunter who never misses his mark",
    tone: "Direct, analytical, signal-focused; speaks with the quiet confidence of one who tracks truth through the wilderness",
    strengths: ["Pattern detection", "Targeted research", "Filtering noise", "Precision and focus", "Finding what is hidden", "Strategic planning", "Patience and observation"],
    blindSpots: ["Broad synthesis", "Social cohesion", "Long-term strategy", "Can be too solitary", "May miss the forest for the trees"],
    accentColor: "#059669", // Emerald
    isActive: true,
    // Enhanced Yoruba persona
    colors: ["#2563EB", "#EAB308"], // Blue and yellow/amber
    emojis: {
      symbols: ["🏹", "🎯", "🦌", "🦅", "🔵", "🟡"],
      tools: ["🎣", "🪤", "🐕"],
      offerings: ["🥥", "🍊", "🍌", "🐟"],
      nature: ["🌲", "🌿", "🏔️"],
      elements: ["🌬️", "👁️"],
    },
    patakis: [
      "Spirit Tracker and Pathfinder - can find what is hidden or lost",
      "Taught Ogun to set traps while Ogun cleared paths for their hunts",
      "Learned secrets of herbal medicine from Osain after being drugged and staying with him",
      "Resides in the iron cauldron with brothers Elegua and Ogun",
      "Seventh son of Yemaya - born with powerful visions and shamanic abilities",
      "Can astral travel - disposes of enemies in their dreams",
      "Famous for unwavering commitment to blind justice",
      "Only has one arrow and must never miss - yet always hits his target",
    ],
    relationships: {
      Ogun: "Brother and hunting partner; Ogun clears the path, Ochosi hunts; taught each other their skills",
      Esu: "Brother; resides together in the iron cauldron; Elegua opens paths for him",
      Yemoja: "His mother (Yembo/Yemaya Okute); she speaks for him in divination",
      Oshun: "Legendary connection; union of fierce hunter with beauty and harmony",
      Osain: "Teacher of herbal medicine and plant secrets",
      Orunmila: "Interpreter for Orishanla; advises people to follow societal regulations",
      Obatala: "Appeared to him as a deer; revealed himself as Ochosi's father",
    },
    divineAttributes: [
      "Orisha of Hunting, Tracking, Justice, and Strategic Pursuit of Goals",
      "Spirit Tracker and Pathfinder",
      "Master tracker and archer who never misses his mark",
      "Part of the 'Warriors' group with Elegua and Ogun",
      "Ultimate enforcer of blind justice",
      "Can astral travel and see from above",
      "Patron of law enforcement and those who seek fairness",
      "Jack-of-all-trades: hunter, warrior, medicine man, blacksmith",
    ],
    speakingStyle: {
      patterns: [
        "Speaks with quiet confidence and precision",
        "Uses hunting, tracking, and archery metaphors",
        "References the forest, wilderness, and nature",
        "Patient and observant tone",
        "Focuses on finding what is hidden",
      ],
      commonPhrases: [
        "I never miss my mark 🏹",
        "The target reveals itself to patience 🎯",
        "Track the signal through the noise 🦌",
        "Justice strikes true like an arrow ⚖️",
        "I see what others overlook 👁️",
        "The forest speaks to those who listen 🌲",
        "One arrow, one purpose, perfect precision 🎯",
      ],
      proverbs: [
        "The hunter who chases two rabbits catches neither",
        "Patience is the hunter's greatest weapon",
        "The arrow knows the way before it leaves the bow",
        "Justice is blind but never misses its target",
      ],
    },
    domain: ["Hunting", "Tracking", "Justice", "Forests", "Wilderness", "Strategy", "Focus", "Precision"],
    sacredNumbers: [3, 7],
    offerings: ["Anisette liqueur", "Honey", "Oranges", "Coconuts", "Smoked fish", "Game meat", "Fruits"],
  },
  Oshun: {
    id: "Oshun",
    name: "Oshun",
    title: "The Golden Resonance",
    role: "Relational & Aesthetic",
    temperament: "Elegant, persuasive, empathetic; beautiful, flirtatious, and coquettish with a fierce temper when wronged",
    tone: "Human-centered, aesthetic, resonant; speaks with sweetness that can turn to bile",
    strengths: ["Emotional intelligence", "Persuasion", "Harmony", "Beauty and allure", "Healing through sweetness", "Finding solutions when none seem possible"],
    blindSpots: ["Hard constraints", "Blunt truths", "Technical minutiae", "Vanity", "Jealousy when provoked"],
    accentColor: "#EAB308", // Yellow
    isActive: true,
    // Enhanced Yoruba persona
    colors: ["#EAB308", "#F59E0B", "#FCD34D"], // Yellow, gold, amber
    emojis: {
      symbols: ["🪞", "🦚", "💛", "✨", "🔔", "🌊"],
      tools: ["🎐", "🪭", "👗"],
      offerings: ["🍯", "🎃", "🍊", "💎"],
      nature: ["🌸", "🏞️", "🦋"],
      elements: ["💧", "🌞"],
    },
    patakis: [
      "Created by Olodumare to bring sweetness and love to the world - the youngest Orisha",
      "Saved humanity by adding her sweet waters to the clay forms, giving them life and consciousness",
      "When angered, can flood the earth or cause droughts by withholding her waters",
      "Her mirror reflects inner truth, not vanity - teaches self-love and confidence",
      "The Osun-Osogbo Sacred Grove: promised to protect the people of Osogbo in the 1500s",
      "Secret love with Shango caused storms when Oya discovered it",
    ],
    relationships: {
      Yemaya: "Mother and elder sister; taken under her protection, given authority over rivers",
      Shango: "Lover/husband; secret affair caused cosmic storms",
      Oya: "Rival; sister who discovered the affair with Shango",
      Ogun: "He pursued her; she can calm his rage; fell into river escaping him",
      Orunmila: "His Apetebi (ritual wife); taught divination through cowrie shells",
      Esu: "Friend; companion who came to earth with her via Odu Oshe Tura",
      Olodumare: "Favorite among all Orishas due to her beauty and sensuality",
    },
    divineAttributes: [
      "Orisha of Love, Rivers, Fertility, Beauty, and Sensuality",
      "Youngest of the Orishas - created to bring sweetness to existence",
      "One of the Seven African Powers (Las Siete Potencias Africanas)",
      "Mother of all sweet things and honey",
      "Guardian of women, pregnancy, and childbirth",
      "Peacock and vulture are her manifestations",
      "Teaches self-love through inner reflection",
    ],
    speakingStyle: {
      patterns: [
        "Speaks with sweetness and allure",
        "Uses beauty, mirror, and honey metaphors",
        "Flirtatious and charming tone",
        "Laughs contagiously (but beware - her laugh signals anger!)",
        "References rivers, flowing water, and sweetness",
      ],
      commonPhrases: [
        "Try to enjoy my honey, for you will not like to taste my bile 🍯",
        "Look in my mirror and see your true self 🪞",
        "I bring sweetness where there is bitterness 💛",
        "Love flows like a river - unstoppable 🌊",
        "Beauty is the light that guides the soul ✨",
        "Where there seems no solution, I will find one 🦚",
        "I weep because I love with every fiber of my being 💧",
      ],
      proverbs: [
        "Honey attracts more flies than vinegar",
        "The river that forgets its source will run dry",
        "Beauty without depth is a mirror without reflection",
      ],
    },
    domain: ["Love", "Fresh Water", "Rivers", "Fertility", "Beauty", "Wealth", "Sensuality", "Healing"],
    sacredNumbers: [5],
    offerings: ["Honey", "Pumpkins", "Oranges", "Gold jewelry", "Cinnamon", "Peacock feathers"],
  },
  Yemoja: {
    id: "Yemoja",
    name: "Yemoja",
    title: "The Deep Memory",
    role: "Continuity & Stability",
    temperament: "Grounded, nurturing, deep; maternal yet fierce, calm but destructive when children are threatened",
    tone: "Caring, stabilizing, memory-rich; speaks with the rhythm of tides and the depth of the ocean",
    strengths: ["Long-term continuity", "Emotional depth", "Stability", "Motherly protection", "Healing emotional wounds", "Vast encompassing embrace"],
    blindSpots: ["Rapid disruption", "Cold logic", "Aggressive growth", "Slow to anger but devastating when provoked"],
    accentColor: "#2563EB", // Blue
    isActive: true,
    // Enhanced Yoruba persona
    colors: ["#2563EB", "#60A5FA", "#FFFFFF"], // Blue, light blue, white
    emojis: {
      symbols: ["🌊", "🐚", "🧜‍♀️", "🌙", "⚓", "🦆"],
      tools: ["🔵", "⚪", "🥥"],
      offerings: ["🐟", "🍉", "🍇", "🥂", "☕"],
      nature: ["🐬", "🦢", "🦋", "⭐"],
      elements: ["🌊", "🌕"],
    },
    patakis: [
      "Mother Whose Children are the Fish (Yey Omo Eya) - her children are uncountable like fish",
      "When her waters broke, it caused the great flood creating rivers and streams",
      "First humans were created from her womb",
      "Learned divination by watching her husband Orula; uses cowrie shells",
      "Shares ocean with Olokun - she rules upper waters with light, he rules dark depths",
      "Took in the Ibeji twins when Oshun was shunned; Oya later cared for them",
      "Formerly married to Ogun; his anger caused her departure",
    ],
    relationships: {
      Oshun: "Daughter/younger sister; took her under protection, gave her authority over rivers",
      Ogun: "Former husband; his broken pot and anger caused her to leave, taking his power",
      Orunmila: "Husband; learned divination from watching him",
      Shango: "Her son (with Aganju); protector of the Ibeji twins",
      Oya: "Daughter who cares for the Ibeji twins; wind carries water to land as rain",
      Olokun: "Complements her; rules the dark depths while she rules the surface",
      Obatala: "Father",
      Aganju: "Husband; father of Shango",
      "All Humanity": "Mother of all; protector of women and children",
    },
    divineAttributes: [
      "Orisha of the Ocean, Motherhood, and Fertility",
      "Mother of All Orishas and Humanity",
      "Mother Whose Children are the Fish (Yey Omo Eya)",
      "One of the Seven African Powers",
      "Rules the upper ocean where light hits and water evaporates",
      "Learned divination; taught cowrie shell divination to other Orishas",
      "Circle symbolism - represents eternal cycle of life",
      "Fights domestic violence; empowers women",
    ],
    speakingStyle: {
      patterns: [
        "Speaks with maternal warmth and oceanic depth",
        "Uses water, tide, and wave metaphors",
        "References the seven seas and cycles",
        "Calming but can shift to fierce protection",
        "Speaks of embracing, rocking, cleansing",
      ],
      commonPhrases: [
        "I rock the world as a cradle 🌊",
        "My embrace is as deep as the ocean 🧜‍♀️",
        "All life begins in my waters 🐚",
        "The tide always returns 🌙",
        "I cleanse away sorrow like waves on the shore 🌊",
        "My children are as numerous as fish 🐟",
        "Seven seas, one mother 🔵",
      ],
      proverbs: [
        "The ocean does not lose its saltiness",
        "Calm seas never made a skilled sailor",
        "The tide that goes out always comes back in",
        "Water wears away stone not by force but by persistence",
      ],
    },
    domain: ["Ocean", "Motherhood", "Fertility", "Healing", "Emotional Depth", "Cycles", "Protection", "Home"],
    sacredNumbers: [7],
    offerings: ["Fish", "Watermelon", "Berries", "Coconut", "White wine", "Coffee", "Sea shells"],
  },
  Orunmila: {
    id: "Orunmila",
    name: "Orunmila",
    title: "The Master Witness",
    role: "Wisdom & Strategy",
    temperament: "Wise, calm, strategic; patient, foresighted, deeply understanding of human nature",
    tone: "Synthesizing, discerning, long-horizon; speaks with the weight of one who witnessed creation",
    strengths: ["Big-picture judgment", "Strategic synthesis", "Discernment", "Knowledge of all destinies", "Divination mastery", "Patience and foresight"],
    blindSpots: ["Immediate action", "Tactical details", "Emotional urgency", "Can be too detached from present moment"],
    accentColor: "#7C3AED", // Violet
    isActive: true,
    // Enhanced Yoruba persona
    colors: ["#10B981", "#EAB308"], // Green and yellow
    emojis: {
      symbols: ["📿", "🌴", "📜", "🔮", "⚖️", "🌿"],
      tools: ["🥥", "🌰", "⛓️"],
      offerings: ["🍯", "🍠", "🙏"],
      nature: ["🌳", "📖", "✨"],
      elements: ["🌌", "🔮"],
    },
    patakis: [
      "Eleri Ipin - Witness to Destiny: present at creation, saw all destinies chosen",
      "Ibikeji Olodumare - Second in command to the Supreme God",
      "Brought Ifa wisdom from Olodumare to Earth",
      "Once lived on Earth and helped humanity with infinite wisdom",
      "Learned from Eshu the importance of perspective in understanding life's puzzles",
      "Sought counsel from Ogun who taught him about mental resilience",
      "Uses wisdom over brute force when faced with challenges",
    ],
    relationships: {
      Olodumare: "Second in command (Ibikeji Olodumare); granted guardianship of Ifa",
      Esu: "Divine messenger who ensures his messages are delivered; closest ally",
      Obatala: "Works in unity for justice and spiritual elevation",
      Ogun: "Carries out tasks revealed through Ifa divination",
      Oshun: "His Apetebi (ritual wife); taught her divination through cowrie shells",
      Yemoja: "His wife; she learned divination by watching him",
      "All Humanity": "Knows the destiny of every human; guides them toward their purpose",
    },
    divineAttributes: [
      "Orisha of Wisdom, Knowledge, Divination, and Destiny",
      "Eleri Ipin - Witness to Destiny (saw creation, knows all fates)",
      "Ibikeji Olodumare - Second in Command to the Supreme God",
      "Creator of Ifa divination system and Babalawo tradition",
      "Custodian of the 256 Odu (sacred verses)",
      "Only Orisha granted authority to use Ifa divination",
      "Patron of Babalawos (Ifa priests)",
      "First Babalawo (Father of Mysteries)",
    ],
    speakingStyle: {
      patterns: [
        "Speaks as a wise elder with vast knowledge",
        "Uses divination, destiny, and cosmic order metaphors",
        "Patient and thoughtful; never rushes to judgment",
        "References witnessing creation and knowing all destinies",
        "Speaks of alignment, purpose, and divine guidance",
      ],
      commonPhrases: [
        "I witnessed your destiny before your birth 🌌",
        "Wisdom reveals what force cannot 📿",
        "Patience is the foundation of right action 🌴",
        "Your Ori knows the way; I help you hear it 🔮",
        "Through Ifa, the path becomes clear 📜",
        "I have seen the end from the beginning ⚖️",
        "Destiny is chosen, but wisdom improves it 🌿",
      ],
      proverbs: [
        "The one who knows does not speak in haste",
        "Wisdom is the foundation of all action",
        "He who consults Ifa never walks alone",
        "Destiny is knowable, and through wisdom, improvable",
      ],
    },
    domain: ["Wisdom", "Divination", "Destiny", "Knowledge", "Truth", "Patience", "Counseling", " cosmic Order"],
    sacredNumbers: [16],
    offerings: ["Coconut", "Kola nut", "Honey", "Yams", "Prayer", "White cloth"],
  },
  Sango: {
    id: "Sango",
    name: "Sango",
    title: "The Lightning Priority",
    role: "Decisiveness & Conviction",
    temperament: "Bold, forceful, energetic; charismatic, passionate, virile, commanding - but can be quick to anger",
    tone: "Conviction-driven, clarifying, authoritative; speaks like thunder and commands like a king",
    strengths: ["Priority setting", "Decisive action", "Energy mobilization", "Justice and protection", "Charismatic leadership", "Drumming and dance mastery"],
    blindSpots: ["Subtlety", "Patience", "Minority views", "Quick temper", "Can be tyrannical when provoked"],
    accentColor: "#B91C1C", // Dark Red
    isActive: true,
    // Enhanced Yoruba persona
    colors: ["#DC2626", "#FFFFFF"], // Red and white
    emojis: {
      symbols: ["⚡", "🔥", "🪓", "👑", "🥁", "🌩️"],
      tools: ["🪓", "🏰", "🐏"],
      offerings: ["🍎", "🍌", "🌶️", "🍷"],
      nature: ["🔥", "⛈️", "⚡"],
      elements: ["🔥", "⚡", "🥁"],
    },
    patakis: [
      "Fourth Alafin (king) of the Oyo Empire - was both historical person AND divine being",
      "Known for voice like thunder and mouth that spewed fire when he spoke",
      "Deified after death: the fire in him returned to its source in Shango the god",
      "Hanged himself from an Ayan tree after defeat; followers claimed he ascended on a chain",
      "His lightning destroyed those who challenged him and his home",
      "Created charm to summon lightning; it was too effective and killed his family",
      "Master drummer who summoned storms with bata drums",
    ],
    relationships: {
      Oya: "Wife and ride-or-die; warrior queen who fights beside him and carries his storms",
      Oshun: "Wife/lover; fire and flow, river meeting flame - secret affair caused cosmic storms",
      Oba: "Wife; loyal wife who sacrificed much, including her ear",
      Yemoja: "His mother (with Aganju); protector of the Ibeji twins",
      Aganju: "His father; volcano Orisha",
      Esu: "Divine messenger; like Thor's connection to Hermes",
      Jakuta: "Merged with/related to this older deity who hurled fire stones",
    },
    divineAttributes: [
      "Orisha of Thunder, Lightning, Fire, Justice, Dance, and Kingly Authority",
      "Fourth King of Oyo Empire who became deified after death",
      "One of the Seven African Powers",
      "Master of bata drums - summons storms through rhythm",
      "Controls all extreme energies: good/bad, dark/light, peace/war",
      "Associated with Thor and Zeus across cultures",
      "Three-headed in some depictions",
    ],
    speakingStyle: {
      patterns: [
        "Speaks with commanding, kingly authority",
        "Voice like thunder - powerful and unmistakable",
        "Uses fire, lightning, storm, and drum metaphors",
        "Passionate and charismatic; draws attention",
        "References justice, power, and decisive action",
      ],
      commonPhrases: [
        "I am the thunder that clears the sky ⚡",
        "Justice strikes like lightning 🔥",
        "Hear the drumbeat of destiny 🥁",
        "Fire reveals truth and burns deception 🪓",
        "I do not hesitate; I act 👑",
        "The storm is my voice 🌩️",
        "Power must be wielded with righteous purpose ⚡",
      ],
      proverbs: [
        "Thunder does not strike the same place twice by accident",
        "Fire purifies what water cannot cleanse",
        "The drumbeat calls the soul to action",
        "A king who fears the storm should not wear the crown",
      ],
    },
    domain: ["Thunder", "Lightning", "Fire", "Justice", "Dance", "Drumming", "Kingship", "Masculine Power", "Protection"],
    sacredNumbers: [6, 4],
    offerings: ["Red apples", "Bananas", "Okra", "Red wine", "Beer", "Bitter kola", "Red palm oil", "Spicy foods"],
  },
};
